const mongoose = require("mongoose");

// create a database schema for storing Party information
const PartySchema = mongoose.Schema({
    // party id -- randomly generated by frontend?
    partyId: {
        type: String,
        required: true,
    },
    // host nickname/id
    host: {
        type: String,
        required: true,
    },
    // list containing all party members (catch if exceeds maximum party size)
    memberList: {
        type: Array,
        required: true,
    },
    // list containing all restaurants generated by original parameters
    restaurantList: {
        type: Array,
        required: true,
    },
    isClosed: {
        type: Boolean,
        default: false,
    },
    // restaurant match results
    matchResults: {
        type: Array,
        default: [],
    },
    // provided in default scheme
    // could be used as another parameter for authentification?
    createdAt: {
        type: Date,
        default: Date.now(),
    },
});

// export model party with PartySchema
module.exports = mongoose.model("party", PartySchema);